extends Node
## All sound in one place. Autoloaded as `Audio`.
##
## Every clip is generated by tools/make_sounds.py — no sample packs, no
## licences, and every parameter is a number in that file. Rebuild with:
##   python3 tools/make_sounds.py
##
## Yes, space is silent. So was X-Wing's, and every space sim since, because a
## silent dogfight is unreadable: the sound is how you know something is
## shooting at you from behind.

const DIR := "res://assets/audio/"
const CLIPS := ["laser_player", "laser_enemy", "impact", "shield_hit", "hull_hit",
	"explosion", "engine_loop", "afterburner_loop", "lock", "warning", "comms",
	"jump", "ui", "music_calm", "music_combat"]
const LOOPING := ["engine_loop", "afterburner_loop", "music_calm", "music_combat"]

## Ships are hundreds of metres apart, so the default 10 m unit size would make
## everything inaudible. This is the number that decides how big space sounds.
const UNIT_SIZE := 280.0
const MAX_DISTANCE := 5000.0

var streams: Dictionary = {}
var _sfx_bus := 1
var _music_bus := 2

var _engine: AudioStreamPlayer
var _burner: AudioStreamPlayer
var _music_calm: AudioStreamPlayer
var _music_combat: AudioStreamPlayer
var _warn_cd := 0.0
var _combat_mix := 0.0        # 0 = calm, 1 = combat
var _flying := false

func _ready() -> void:
	_build_buses()
	_load_clips()
	_build_players()
	apply_volumes()
	if Settings.has_signal("changed"):
		Settings.changed.connect(apply_volumes)

func _build_buses() -> void:
	AudioServer.add_bus(1)
	AudioServer.set_bus_name(1, "SFX")
	AudioServer.set_bus_send(1, "Master")
	AudioServer.add_bus(2)
	AudioServer.set_bus_name(2, "Music")
	AudioServer.set_bus_send(2, "Master")
	_sfx_bus = AudioServer.get_bus_index("SFX")
	_music_bus = AudioServer.get_bus_index("Music")

func _load_clips() -> void:
	for name in CLIPS:
		var stream: AudioStream = load(DIR + name + ".wav")
		if stream == null:
			push_warning("missing audio clip: " + name)
			continue
		if name in LOOPING and stream is AudioStreamWAV:
			var wav := stream as AudioStreamWAV
			wav.loop_mode = AudioStreamWAV.LOOP_FORWARD
			wav.loop_begin = 0
			wav.loop_end = wav.data.size() / 2      # 16-bit mono
		streams[name] = stream

func _build_players() -> void:
	_engine = _looping_player("engine_loop", _sfx_bus)
	_burner = _looping_player("afterburner_loop", _sfx_bus)
	_music_calm = _looping_player("music_calm", _music_bus)
	_music_combat = _looping_player("music_combat", _music_bus)

func _looping_player(clip: String, bus: int) -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.stream = streams.get(clip)
	p.bus = AudioServer.get_bus_name(bus)
	p.volume_db = -80.0
	p.process_mode = Node.PROCESS_MODE_ALWAYS
	add_child(p)
	return p

# --- volume --------------------------------------------------------------

func apply_volumes() -> void:
	AudioServer.set_bus_volume_db(0, linear_to_db(clampf(Settings.volume_master, 0.0, 1.0)))
	AudioServer.set_bus_volume_db(_sfx_bus, linear_to_db(clampf(Settings.volume_sfx, 0.0, 1.0)))
	AudioServer.set_bus_volume_db(_music_bus, linear_to_db(clampf(Settings.volume_music, 0.0, 1.0)))
	AudioServer.set_bus_mute(0, Settings.volume_master <= 0.001)

# --- one-shots -----------------------------------------------------------

## Positional one-shot. Frees itself; safe to fire from anything, including a
## node that is about to be destroyed.
func play_3d(clip: String, world_pos: Vector3, parent: Node, volume_db := 0.0, pitch := 1.0) -> void:
	if not streams.has(clip) or parent == null or not is_instance_valid(parent):
		return
	var p := AudioStreamPlayer3D.new()
	p.stream = streams[clip]
	p.bus = AudioServer.get_bus_name(_sfx_bus)
	p.unit_size = UNIT_SIZE
	p.max_distance = MAX_DISTANCE
	p.volume_db = volume_db
	p.pitch_scale = pitch
	p.attenuation_model = AudioStreamPlayer3D.ATTENUATION_INVERSE_DISTANCE
	p.doppler_tracking = AudioStreamPlayer3D.DOPPLER_TRACKING_PHYSICS_STEP
	parent.add_child(p)
	p.global_position = world_pos
	p.finished.connect(p.queue_free)
	p.play()

func play_ui(clip: String, volume_db := 0.0, pitch := 1.0) -> void:
	if not streams.has(clip):
		return
	var p := AudioStreamPlayer.new()
	p.stream = streams[clip]
	p.bus = AudioServer.get_bus_name(_sfx_bus)
	p.volume_db = volume_db
	p.pitch_scale = pitch
	p.process_mode = Node.PROCESS_MODE_ALWAYS
	add_child(p)
	p.finished.connect(p.queue_free)
	p.play()

## Cockpit warning tone, rate-limited so a bad minute does not become a siren.
func warn(min_gap := 1.6) -> void:
	if _warn_cd > 0.0:
		return
	_warn_cd = min_gap
	play_ui("warning", -6.0)

# --- flight loops --------------------------------------------------------

func start_flight() -> void:
	_flying = true
	for p in [_engine, _burner, _music_calm, _music_combat]:
		if not p.playing:
			p.play()

func stop_flight() -> void:
	_flying = false
	for p in [_engine, _burner]:
		p.stop()

## Engine note follows the throttle, not the speed: it is the pilot's own
## control that should be audible, so the ship answers when you move the lever.
func update_flight(speed_frac: float, burner: bool, dt: float) -> void:
	if not _flying:
		return
	speed_frac = clampf(speed_frac, 0.0, 1.4)
	_engine.volume_db = lerpf(_engine.volume_db, -26.0 + 14.0 * speed_frac, clampf(dt * 4.0, 0, 1))
	_engine.pitch_scale = lerpf(_engine.pitch_scale, 0.72 + 0.5 * speed_frac, clampf(dt * 4.0, 0, 1))
	var burner_target := -10.0 if burner else -80.0
	_burner.volume_db = lerpf(_burner.volume_db, burner_target, clampf(dt * (6.0 if burner else 2.5), 0, 1))
	_warn_cd = maxf(0.0, _warn_cd - dt)

## Dynamic score, X-Wing's trick: the combat stem fades in fast when something
## is close and hostile, and back out slowly so the tension does not flicker.
func set_threat(level: float, dt: float) -> void:
	if not _flying:
		return
	var rate := 1.6 if level > _combat_mix else 0.35
	_combat_mix = move_toward(_combat_mix, clampf(level, 0.0, 1.0), rate * dt)
	_music_calm.volume_db = linear_to_db(maxf(1.0 - _combat_mix, 0.0001)) - 4.0
	_music_combat.volume_db = linear_to_db(maxf(_combat_mix, 0.0001)) - 4.0

## Release the looping streams on shutdown. Without this the engine reports
## "resources still in use at exit" on every run, and a log with a standing
## error in it is a log nobody reads.
func _notification(what: int) -> void:
	if what == NOTIFICATION_PREDELETE or what == NOTIFICATION_EXIT_TREE \
			or what == NOTIFICATION_WM_CLOSE_REQUEST:
		_release_streams()

func _release_streams() -> void:
	for child in get_children():
		if child is AudioStreamPlayer:
			var p := child as AudioStreamPlayer
			p.stop()
			p.stream = null
	streams.clear()

func music_only() -> void:
	_flying = true
	if not _music_calm.playing:
		_music_calm.play()
		_music_combat.play()
	_combat_mix = 0.0
	_music_calm.volume_db = -4.0
	_music_combat.volume_db = -80.0
	_engine.volume_db = -80.0
	_burner.volume_db = -80.0
